"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ACTIVITY_LOG_COLLECTION = exports.INQUIRY_FOLDER = exports.INQUIRY_COLLECTION = exports.TRANSPARENCY_SEAL_FOLDER = exports.TRANSPARENCY_FOLDER = exports.TRANSPARENCY_SEAL_COLLECTION = exports.TRANSPARENCY_TITLE = exports.NEWS_AND_UPDATES_FOLDER = exports.NEWS_TOTAL_COUNT_COLLECTION = exports.NEWS_ARCHIVES_COLLECTION = exports.NEWS_AND_UPDATES_COLLECTION = void 0;
const NEWS_AND_UPDATES_COLLECTION = "news_and_updates";
exports.NEWS_AND_UPDATES_COLLECTION = NEWS_AND_UPDATES_COLLECTION;
const NEWS_ARCHIVES_COLLECTION = "news_archives";
exports.NEWS_ARCHIVES_COLLECTION = NEWS_ARCHIVES_COLLECTION;
const NEWS_TOTAL_COUNT_COLLECTION = "news_total_count";
exports.NEWS_TOTAL_COUNT_COLLECTION = NEWS_TOTAL_COUNT_COLLECTION;
const TRANSPARENCY_TITLE = "transparency_title";
exports.TRANSPARENCY_TITLE = TRANSPARENCY_TITLE;
const TRANSPARENCY_SEAL_COLLECTION = "transparency_seal"; // Collection name
exports.TRANSPARENCY_SEAL_COLLECTION = TRANSPARENCY_SEAL_COLLECTION;
const TRANSPARENCY_FOLDER = "transparency_folder"; // Folder name
exports.TRANSPARENCY_FOLDER = TRANSPARENCY_FOLDER;
const INQUIRY_COLLECTION = "inquiries"; // Collection name
exports.INQUIRY_COLLECTION = INQUIRY_COLLECTION;
// storage
const NEWS_AND_UPDATES_FOLDER = "news"; // Folder name
exports.NEWS_AND_UPDATES_FOLDER = NEWS_AND_UPDATES_FOLDER;
const TRANSPARENCY_SEAL_FOLDER = "transparency";
exports.TRANSPARENCY_SEAL_FOLDER = TRANSPARENCY_SEAL_FOLDER;
const INQUIRY_FOLDER = "inquiry"; // Folder name
exports.INQUIRY_FOLDER = INQUIRY_FOLDER;
const ACTIVITY_LOG_COLLECTION = "activity_logs";
exports.ACTIVITY_LOG_COLLECTION = ACTIVITY_LOG_COLLECTION;
