"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_1 = require("../middleware/auth");
const validate_1 = require("../middleware/validate");
const activity_log_schema_1 = require("../validation/activity-log.schema");
const activity_log_1 = require("../controller/activity.log");
const router = (0, express_1.Router)();
router.get("/", auth_1.requireAdmin, (0, validate_1.validateQuery)(activity_log_schema_1.getPaginatedActivityLogsSchema), activity_log_1.getPaginatedLogsController);
router.get("/count", auth_1.requireAdmin, activity_log_1.getPaginatedLogsTotalCountController);
router.delete("/", activity_log_1.testDeleteLogsController);
exports.default = router;
