"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const settings_1 = require("../controller/settings");
const auth_1 = require("../middleware/auth");
const validate_1 = require("../middleware/validate");
const settings_schema_1 = require("../validation/settings.schema");
const id_schema_1 = require("../validation/id.schema");
const router = (0, express_1.Router)();
router.get("/", settings_1.getSettingsController);
router.patch("/:id", auth_1.requireAdmin, (0, validate_1.validateParams)(id_schema_1.idSchema), (0, validate_1.validateBody)(settings_schema_1.patchLogSettingsSchema), settings_1.patchSettingsController);
exports.default = router;
